DATA_CENTER/src/Entity/Produits.php
<?php

namespace App\Entity;

use App\Repository\ProduitsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ProduitsRepository::class)]
class Produits
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['produits.index', 'produits.show', 'produits.create'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits.index', 'produits.show', 'produits.create'])]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits.show', 'produits.create'])]
    private ?string $categorie = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits.show', 'produits.create'])]
    private ?string $sous_categorie = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits.show', 'produits.create'])]
    private ?string $cout_unitaire = null;

    #[ORM\Column(length: 255)]
    #[Groups(['produits.show', 'produits.create'])]
    private ?string $prix_unitaire = null;

    /**
     * @var Collection<int, Ventes>
     */
    #[ORM\OneToMany(targetEntity: Ventes::class, mappedBy: 'produit')]
    private Collection $ventes;

    public function __construct()
    {
        $this->ventes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getCategorie(): ?string
    {
        return $this->categorie;
    }

    public function setCategorie(string $categorie): static
    {
        $this->categorie = $categorie;

        return $this;
    }

    public function getSousCategorie(): ?string
    {
        return $this->sous_categorie;
    }

    public function setSousCategorie(string $sous_categorie): static
    {
        $this->sous_categorie = $sous_categorie;

        return $this;
    }

    public function getCoutUnitaire(): ?string
    {
        return $this->cout_unitaire;
    }

    public function setCoutUnitaire(string $cout_unitaire): static
    {
        $this->cout_unitaire = $cout_unitaire;

        return $this;
    }

    public function getPrixUnitaire(): ?string
    {
        return $this->prix_unitaire;
    }

    public function setPrixUnitaire(string $prix_unitaire): static
    {
        $this->prix_unitaire = $prix_unitaire;

        return $this;
    }

    /**
     * @return Collection<int, Ventes>
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Ventes $vente): static
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes->add($vente);
            $vente->setProduit($this);
        }

        return $this;
    }

    public function removeVente(Ventes $vente): static
    {
        if ($this->ventes->removeElement($vente)) {
            // set the owning side to null (unless already changed)
            if ($vente->getProduit() === $this) {
                $vente->setProduit(null);
            }
        }

        return $this;
    }
}

DATA_CENTER/src/Form/ProduitsType.php
<?php

namespace App\Form;

use App\Entity\Produits;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProduitsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('categorie')
            ->add('sous_categorie')
            ->add('cout_unitaire')
            ->add('prix_unitaire')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Produits::class,
        ]);
    }
}

DATA_CENTER/src/Controller/ProduitsController.php
<?php

namespace App\Controller;

use App\Entity\Produits;
use App\Form\ProduitsType;
use App\Repository\ProduitsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/produits')]
final class ProduitsController extends AbstractController
{
    #[Route(name: 'app_produits_index', methods: ['GET'])]
    public function index(ProduitsRepository $produitsRepository): Response
    {
        return $this->render('produits/index.html.twig', [
            'produits' => $produitsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_produits_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $produit = new Produits();
        $form = $this->createForm(ProduitsType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($produit);
            $entityManager->flush();

            return $this->redirectToRoute('app_produits_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produits/new.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produits_show', methods: ['GET'])]
    public function show(Produits $produit): Response
    {
        return $this->render('produits/show.html.twig', [
            'produit' => $produit,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_produits_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Produits $produit, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ProduitsType::class, $produit);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_produits_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('produits/edit.html.twig', [
            'produit' => $produit,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_produits_delete', methods: ['POST'])]
    public function delete(Request $request, Produits $produit, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$produit->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($produit);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_produits_index', [], Response::HTTP_SEE_OTHER);
    }
}

DATA_CENTER/templates/produits/_delete_form.html.twig
<form method="post" action="{{ path('app_produits_delete', {'id': produit.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ produit.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

DATA_CENTER/templates/produits/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

DATA_CENTER/templates/produits/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Modifier : {{ produit.nom }}{% endblock %}
{% block titre %}Modifier : {{ produit.nom }}{% endblock %}
{% block btnAction %}
<div class="col">{{ include('produits/_delete_form.html.twig') }}</div>
{% endblock %}

{% block body %}
    {{ include('produits/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
{% endblock %}

DATA_CENTER/templates/produits/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Liste des produits{% endblock %}
{% block titre %}Liste des produits{% endblock %}
{% block btnAction %}<a href="{{ path('app_produits_new') }}" class="btn btn-primary">Ajouter</a>{% endblock %}

{% block body %}
<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Nom</th>
                <th>Categorie</th>
                <th>Sous_categorie</th>
                <th>Cout_unitaire</th>
                <th>Prix_unitaire</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for produit in produits %}
            <tr>
                <td>{{ produit.nom }}</td>
                <td>{{ produit.categorie }}</td>
                <td>{{ produit.sousCategorie }}</td>
                <td>{{ produit.coutUnitaire }}</td>
                <td>{{ produit.prixUnitaire }}</td>
                <td>
                    <a href="{{ path('app_produits_show', {'id': produit.id}) }}" class="btn btn-secondary">show</a>
                    <a href="{{ path('app_produits_edit', {'id': produit.id}) }}" class="btn btn-secondary">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Pas de produits</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

DATA_CENTER/templates/produits/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Ajouter un produit{% endblock %}
{% block titre %}Ajouter un produit{% endblock %}

{% block body %}
    {{ include('produits/_form.html.twig', {'button_label': 'Enregistrer'}) }}
{% endblock %}

DATA_CENTER/templates/produits/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}{{ produit.nom }}{% endblock %}
{% block titre %}{{ produit.nom }}{% endblock %}
{% block btnAction %}
<div class="col"><a href="{{ path('app_produits_edit', {'id': produit.id}) }}" class="btn btn-primary">Modifier</a></div>
<div class="col">{{ include('produits/_delete_form.html.twig') }}</div>
{% endblock %}

{% block body %}

    <table class="table">
        <tbody>
            <tr>
                <th>Nom</th>
                <td>{{ produit.nom }}</td>
            </tr>
            <tr>
                <th>Categorie</th>
                <td>{{ produit.categorie }}</td>
            </tr>
            <tr>
                <th>Sous_categorie</th>
                <td>{{ produit.sousCategorie }}</td>
            </tr>
            <tr>
                <th>Cout_unitaire</th>
                <td>{{ produit.coutUnitaire }}</td>
            </tr>
            <tr>
                <th>Prix_unitaire</th>
                <td>{{ produit.prixUnitaire }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}