DATA_CENTER/src/Entity/Clients.php
<?php

namespace App\Entity;

use App\Repository\ClientsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ClientsRepository::class)]
class Clients
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups(['clients.index', 'clients.show'])]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Groups(['clients.index', 'clients.show'])]
    private ?string $client = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups(['clients.show'])]
    private ?string $adresse = null;

    #[ORM\Column]
    #[Groups(['clients.show'])]
    private ?int $code_postal = null;

    #[ORM\Column(length: 255)]
    #[Groups(['clients.show'])]
    private ?string $ville = null;

    #[ORM\Column(length: 255)]
    #[Groups(['clients.show'])]
    private ?string $telephone = null;

    #[ORM\Column(length: 255)]
    #[Groups(['clients.show'])]
    private ?string $civilite = null;

    #[ORM\Column(length: 255)]
    #[Groups(['clients.show'])]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    #[Groups(['clients.show'])]
    private ?string $nom = null;

    /**
     * @var Collection<int, Ventes>
     */
    #[ORM\OneToMany(targetEntity: Ventes::class, mappedBy: 'client', orphanRemoval: true)]
    private Collection $ventes;

    public function __construct()
    {
        $this->ventes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?string
    {
        return $this->client;
    }

    public function setClient(string $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?int
    {
        return $this->code_postal;
    }

    public function setCodePostal(int $code_postal): static
    {
        $this->code_postal = $code_postal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(string $telephone): static
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getCivilite(): ?string
    {
        return $this->civilite;
    }

    public function setCivilite(string $civilite): static
    {
        $this->civilite = $civilite;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * @return Collection<int, Ventes>
     */
    public function getVentes(): Collection
    {
        return $this->ventes;
    }

    public function addVente(Ventes $vente): static
    {
        if (!$this->ventes->contains($vente)) {
            $this->ventes->add($vente);
            $vente->setClient($this);
        }

        return $this;
    }

    public function removeVente(Ventes $vente): static
    {
        if ($this->ventes->removeElement($vente)) {
            // set the owning side to null (unless already changed)
            if ($vente->getClient() === $this) {
                $vente->setClient(null);
            }
        }

        return $this;
    }
}

DATA_CENTER/src/Form/ClientsType.php
<?php

namespace App\Form;

use App\Entity\Clients;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ClientsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('client')
            ->add('adresse')
            ->add('code_postal')
            ->add('ville')
            ->add('telephone')
            ->add('civilite')
            ->add('prenom')
            ->add('nom')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Clients::class,
        ]);
    }
}

DATA_CENTER/src/Controller/ClientsController.php
<?php

namespace App\Controller;

use App\Entity\Clients;
use App\Form\ClientsType;
use App\Repository\ClientsRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/clients')]
final class ClientsController extends AbstractController
{
    #[Route(name: 'app_clients_index', methods: ['GET'])]
    public function index(ClientsRepository $clientsRepository): Response
    {
        return $this->render('clients/index.html.twig', [
            'clients' => $clientsRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_clients_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $client = new Clients();
        $form = $this->createForm(ClientsType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($client);
            $entityManager->flush();

            return $this->redirectToRoute('app_clients_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('clients/new.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_clients_show', methods: ['GET'])]
    public function show(Clients $client): Response
    {
        return $this->render('clients/show.html.twig', [
            'client' => $client,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_clients_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Clients $client, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ClientsType::class, $client);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_clients_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('clients/edit.html.twig', [
            'client' => $client,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_clients_delete', methods: ['POST'])]
    public function delete(Request $request, Clients $client, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$client->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($client);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_clients_index', [], Response::HTTP_SEE_OTHER);
    }
}

DATA_CENTER/templates/clients/_delete_form.html.twig
<form method="post" action="{{ path('app_clients_delete', {'id': client.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ client.id) }}">
    <button class="btn btn-danger">Supprimer</button>
</form>

DATA_CENTER/templates/clients/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

DATA_CENTER/templates/clients/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Modifier : {{ client.client }}{% endblock %}
{% block titre %}Modifier : {{ client.client }}{% endblock %}
{% block btnAction %}
<div class="col">{{ include('clients/_delete_form.html.twig') }}</div>
{% endblock %}

{% block body %}    

    {{ include('clients/_form.html.twig', {'button_label': 'Mettre à jour'}) }}

{% endblock %}

DATA_CENTER/templates/clients/index.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Liste des Clients{% endblock %}

{% block titre %}Liste des Clients{% endblock %}
{% block btnAction %}<a href="{{ path('app_clients_new') }}" class="btn btn-primary">Ajouter</a>{% endblock %}

{% block body %}
<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>Client</th>
                <th>Adresse</th>
                <th>Code postal</th>
                <th>Ville</th>
                <th>Telephone</th>
                <th>Civilite</th>
                <th>Prenom</th>
                <th>Nom</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for client in clients %}
            <tr>
                <td>{{ client.client }}</td>
                <td>{{ client.adresse }}</td>
                <td>{{ client.codePostal }}</td>
                <td>{{ client.ville }}</td>
                <td>{{ client.telephone }}</td>
                <td>{{ client.civilite }}</td>
                <td>{{ client.prenom }}</td>
                <td>{{ client.nom }}</td>
                <td>
                    <a href="{{ path('app_clients_show', {'id': client.id}) }}" class="btn btn-secondary">Afficher</a>
                    <a href="{{ path('app_clients_edit', {'id': client.id}) }}" class="btn btn-secondary">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">Pas de clients</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

DATA_CENTER/templates/clients/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Ajouter un client{% endblock %}
{% block titre %}Ajouter un client{% endblock %}

{% block body %}

    {{ include('clients/_form.html.twig', {'button_label': 'Enregistrer'}) }}

{% endblock %}

DATA_CENTER/templates/clients/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}{{ client.client }}{% endblock %}
{% block titre %}{{ client.client }}{% endblock %}
{% block btnAction %}
<div class="col"><a href="{{ path('app_clients_edit', {'id': client.id}) }}" class="btn btn-primary">Modifier</a></div>
<div class="col">{{ include('clients/_delete_form.html.twig') }}</div>
{% endblock %}

{% block body %}

    <table class="table">
        <tbody>
            <tr>
                <th>Client</th>
                <td>{{ client.client }}</td>
            </tr>
            <tr>
                <th>Adresse</th>
                <td>{{ client.adresse }}</td>
            </tr>
            <tr>
                <th>Code_postal</th>
                <td>{{ client.codePostal }}</td>
            </tr>
            <tr>
                <th>Ville</th>
                <td>{{ client.ville }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ client.telephone }}</td>
            </tr>
            <tr>
                <th>Civilite</th>
                <td>{{ client.civilite }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ client.prenom }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ client.nom }}</td>
            </tr>
        </tbody>
    </table>
{% endblock %}