DATA_CENTER/src/Entity/Ventes.php
<?php

namespace App\Entity;

use App\Repository\VentesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: VentesRepository::class)]
class Ventes
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $n_commande = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_commande = null;

    #[ORM\ManyToOne(inversedBy: 'ventes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Clients $client = null;

    #[ORM\Column(length: 255)]
    private ?string $canal = null;

    #[ORM\ManyToOne(inversedBy: 'ventes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Produits $produit = null;

    #[ORM\Column]
    private ?int $quantite = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_livraison = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNCommande(): ?string
    {
        return $this->n_commande;
    }

    public function setNCommande(string $n_commande): static
    {
        $this->n_commande = $n_commande;

        return $this;
    }

    public function getDateCommande(): ?\DateTimeInterface
    {
        return $this->date_commande;
    }

    public function setDateCommande(\DateTimeInterface $date_commande): static
    {
        $this->date_commande = $date_commande;

        return $this;
    }

    public function getClient(): ?Clients
    {
        return $this->client;
    }

    public function setClient(?Clients $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getCanal(): ?string
    {
        return $this->canal;
    }

    public function setCanal(string $canal): static
    {
        $this->canal = $canal;

        return $this;
    }

    public function getProduit(): ?Produits
    {
        return $this->produit;
    }

    public function setProduit(?Produits $produit): static
    {
        $this->produit = $produit;

        return $this;
    }

    public function getQuantite(): ?int
    {
        return $this->quantite;
    }

    public function setQuantite(int $quantite): static
    {
        $this->quantite = $quantite;

        return $this;
    }

    public function getDateLivraison(): ?\DateTimeInterface
    {
        return $this->date_livraison;
    }

    public function setDateLivraison(\DateTimeInterface $date_livraison): static
    {
        $this->date_livraison = $date_livraison;

        return $this;
    }
}

DATA_CENTER/src/Form/VentesType.php
<?php

namespace App\Form;

use App\Entity\Clients;
use App\Entity\Produits;
use App\Entity\Ventes;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class VentesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('n_commande')
            ->add('date_commande', null, [
                'widget' => 'single_text',
            ])
            ->add('canal')
            ->add('quantite')
            ->add('date_livraison', null, [
                'widget' => 'single_text',
            ])
            ->add('client', EntityType::class, [
                'class' => Clients::class,
                'choice_label' => 'id',
            ])
            ->add('produit', EntityType::class, [
                'class' => Produits::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ventes::class,
        ]);
    }
}

DATA_CENTER/src/Controller/VentesController.php
<?php

namespace App\Controller;

use App\Entity\Ventes;
use App\Form\VentesType;
use App\Repository\VentesRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/ventes')]
final class VentesController extends AbstractController
{
    #[Route(name: 'app_ventes_index', methods: ['GET'])]
    public function index(VentesRepository $ventesRepository): Response
    {
        return $this->render('ventes/index.html.twig', [
            'ventes' => $ventesRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_ventes_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $vente = new Ventes();
        $form = $this->createForm(VentesType::class, $vente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($vente);
            $entityManager->flush();

            return $this->redirectToRoute('app_ventes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ventes/new.html.twig', [
            'vente' => $vente,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ventes_show', methods: ['GET'])]
    public function show(Ventes $vente): Response
    {
        return $this->render('ventes/show.html.twig', [
            'vente' => $vente,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_ventes_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Ventes $vente, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(VentesType::class, $vente);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_ventes_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('ventes/edit.html.twig', [
            'vente' => $vente,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_ventes_delete', methods: ['POST'])]
    public function delete(Request $request, Ventes $vente, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$vente->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($vente);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_ventes_index', [], Response::HTTP_SEE_OTHER);
    }
}

DATA_CENTER/templates/ventes/_delete_form.html.twig
<form method="post" action="{{ path('app_ventes_delete', {'id': vente.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ vente.id) }}">
    <button class="btn">Delete</button>
</form>

DATA_CENTER/templates/ventes/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

DATA_CENTER/templates/ventes/edit.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Modifier : {{ vente.nCommande }}{% endblock %}
{% block titre %}Modifier : {{ vente.nCommande }}{% endblock %}
{% block btnAction %}
<div class="col">{{ include('ventes/_delete_form.html.twig') }}</div>
{% endblock %}

{% block body %}
    {{ include('ventes/_form.html.twig', {'button_label': 'Mettre à jour'}) }}
{% endblock %}

DATA_CENTER/templates/ventes/index.html.twig
{% extends 'admin.html.twig' %}
{% block title %}Liste des Ventes{% endblock %}

{% block titre %}Liste des Ventes{% endblock %}
{% block btnAction %}<a href="{{ path('app_ventes_new') }}" class="btn btn-primary">Ajouter</a>{% endblock %}

{% block body %}
<div class="table-responsive small">
    <table class="table table-striped table-sm">
        <thead>
            <tr>
                <th>N_commande</th>
                <th>Date_commande</th>
                <th>Canal</th>
                <th>Quantite</th>
                <th>Date_livraison</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        {% for vente in ventes %}
            <tr>
                <td>{{ vente.nCommande }}</td>
                <td>{{ vente.dateCommande ? vente.dateCommande|date('Y-m-d') : '' }}</td>
                <td>{{ vente.canal }}</td>
                <td>{{ vente.quantite }}</td>
                <td>{{ vente.dateLivraison ? vente.dateLivraison|date('Y-m-d') : '' }}</td>
                <td>
                    <a href="{{ path('app_ventes_show', {'id': vente.id}) }}" class="btn btn-secondary">Afficher</a>
                    <a href="{{ path('app_ventes_edit', {'id': vente.id}) }}" class="btn btn-secondary">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

DATA_CENTER/templates/ventes/new.html.twig
{% extends 'admin.html.twig' %}

{% block title %}Ajouter une vente{% endblock %}
{% block titre %}Ajouter une vente{% endblock %}

{% block body %}
    {{ include('ventes/_form.html.twig', {'button_label': 'Enregistrer'}) }}
{% endblock %}

DATA_CENTER/templates/ventes/show.html.twig
{% extends 'admin.html.twig' %}

{% block title %}{{ vente.nCommande }}{% endblock %}
{% block titre %}{{ vente.nCommande }}{% endblock %}
{% block btnAction %}
<div class="col"><a href="{{ path('app_ventes_edit', {'id': vente.id}) }}" class="btn btn-primary">Modifier</a></div>
<div class="col">{{ include('ventes/_delete_form.html.twig') }}</div>
{% endblock %}

{% block body %}

    <table class="table">
        <tbody>
            <tr>
                <th>N_commande</th>
                <td>{{ vente.nCommande }}</td>
            </tr>
            <tr>
                <th>Date_commande</th>
                <td>{{ vente.dateCommande ? vente.dateCommande|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Canal</th>
                <td>{{ vente.canal }}</td>
            </tr>
            <tr>
                <th>Quantite</th>
                <td>{{ vente.quantite }}</td>
            </tr>
            <tr>
                <th>Date_livraison</th>
                <td>{{ vente.dateLivraison ? vente.dateLivraison|date('Y-m-d') : '' }}</td>
            </tr>
        </tbody>
    </table>    
{% endblock %}